# Generated by Django 3.2.7 on 2021-09-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20210919_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_url', models.URLField(unique=True, verbose_name='Ссылка на вакансию')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('company', models.CharField(max_length=250, verbose_name='Работодатель')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.city', verbose_name='Город')),
                ('programming_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.programminglanguage', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
